# Generated by Django 5.1.2 on 2024-10-20 12:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('father_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент ',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(default=datetime.datetime(2024, 10, 20, 12, 18, 43, 392652), verbose_name='Дата и время первой отправки рассылки')),
                ('next_data_time', models.DateTimeField(default=datetime.datetime(2024, 10, 20, 12, 18, 43, 392665), verbose_name='Дата и время следующей отправки рассылки')),
                ('periodicity', models.CharField(choices=[('once_day', 'Раз в день'), ('once_week', 'Раз в неделю'), ('once_month', 'Раз в месяц')], default='once_day', max_length=10, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('started', 'Запущена'), ('created', 'Создана'), ('completed', 'Завершена')], default='created', max_length=9, verbose_name='Статус рассылки')),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ManyToManyField(to='mainapp.client', verbose_name='Клиенты')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рассылка ',
                'verbose_name_plural': 'Рассылки',
                'permissions': [('can_view_mailing', 'Может просматривать любые рассылки'), ('can_disable_mailing', 'Может отключать рассылки')],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последней попытки отправить рассылку')),
                ('is_attempt', models.BooleanField(default=True, verbose_name='Статус попытки')),
                ('email_answer', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_letter', models.CharField(max_length=350, verbose_name='Тема письма')),
                ('body_letter', models.TextField(verbose_name='Тело письма')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Письмо ',
                'verbose_name_plural': 'Письма',
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.message', verbose_name='Сообщение'),
        ),
    ]
